// <auto-generated />
using System;
using GundamEvolutionDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GundamEvolutionDatabase.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230503022812_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GundamEvolutionDatabase.Models.Ability", b =>
                {
                    b.Property<int>("AbilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityID"), 1L, 1);

                    b.Property<string>("AbilityAttributeData1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeData2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeData3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Ultimate")
                        .HasColumnType("bit");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("AbilityID");

                    b.HasIndex("UnitID");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("GundamEvolutionDatabase.Models.Unit", b =>
                {
                    b.Property<int?>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UnitID"), 1L, 1);

                    b.Property<int?>("DashLimit")
                        .HasColumnType("int");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int?>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shield")
                        .HasColumnType("int");

                    b.HasKey("UnitID");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GundamEvolutionDatabase.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponID"), 1L, 1);

                    b.Property<string>("AbilityAttributeData1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeData2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityAttributeName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DamageBody")
                        .HasColumnType("int");

                    b.Property<int?>("DamageHead")
                        .HasColumnType("int");

                    b.Property<int?>("DamageLimb")
                        .HasColumnType("int");

                    b.Property<int?>("FallOffDistance")
                        .HasColumnType("int");

                    b.Property<int?>("MagazineSize")
                        .HasColumnType("int");

                    b.Property<int?>("ReloadTimeAlt")
                        .HasColumnType("int");

                    b.Property<int?>("ReloadTimeStandard")
                        .HasColumnType("int");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.Property<string>("WeaponName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponSwitchTime")
                        .HasColumnType("int");

                    b.HasKey("WeaponID");

                    b.HasIndex("UnitID");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("GundamEvolutionDatabase.Models.Ability", b =>
                {
                    b.HasOne("GundamEvolutionDatabase.Models.Unit", null)
                        .WithMany("Abilities")
                        .HasForeignKey("UnitID");
                });

            modelBuilder.Entity("GundamEvolutionDatabase.Models.Weapon", b =>
                {
                    b.HasOne("GundamEvolutionDatabase.Models.Unit", null)
                        .WithMany("Weapons")
                        .HasForeignKey("UnitID");
                });

            modelBuilder.Entity("GundamEvolutionDatabase.Models.Unit", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
